# Generated by Django 3.2.6 on 2021-08-23 12:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.TextField(max_length=500)),
                ('joining_date', models.DateField(verbose_name='datetime')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('Religion', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('teacher_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='teacher/')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('blood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.blood')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.gender')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.group')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.section')),
            ],
        ),
    ]
