# Generated by Django 3.2.6 on 2021-08-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(verbose_name='Joining Date'),
        ),
    ]
