# Generated by Django 3.2.6 on 2021-08-25 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_exam_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='marks',
            new_name='assignment_mark',
        ),
        migrations.AddField(
            model_name='mark',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mark',
            name='exam_mark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
