# Generated by Django 3.2.6 on 2021-08-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210826_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='student_resister_no',
            field=models.CharField(blank=True, max_length=999999999, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='assignment_mark',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='exam_mark',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
    ]
